// src/lib/components/pages/ResultsPage.svelte
<script lang="ts">
  let { response, query }: { response: any; query: string } = $props();
  import Search from "lucide-svelte/icons/search";
  import Link from "lucide-svelte/icons/link";

  function stripTrailingSlash(str: string) {
    return str.endsWith("/") ? str.slice(0, -1) : str;
  }
</script>

<svelte:head>
  {#if response.Abstract}
    <meta name="description" content={response.Abstract} />
    <title>{response.Heading ?? "Zook"}</title>
    <meta name="og:image" content={`https://duckduckgo.com${response.Image}`} />
  {/if}
</svelte:head>

{#if response.Heading}
  <h1>{response.Heading}</h1>
{/if}

{#if response.Abstract}
  <aside>
    <div class="flex flex-col gap-6 md:flex-row">
      {#if response.Image}
        <img
          src={`https://duckduckgo.com${response.Image}`}
          alt={response.Heading}
          class="mb-2 h-fit w-32 rounded object-cover object-top md:order-1"
        />
      {/if}

      <p>
        {response.Abstract}
      </p>
    </div>
  </aside>
{/if}

{#if response.Results.length}
  <h2 class="text-nord6/50">links</h2>

  <ul>
    {#each response.Results as result}
      {@const url = new URL(result.FirstURL)}
      {#if result.FirstURL}
        <li class="mb-6">
          <a href={result.FirstURL} class="group flex items-center gap-2">
            <Link class="size-4 shrink-0" />

            <span class="truncate group-hover:underline">
              {url.hostname.replace("www.", "")}
              {stripTrailingSlash(url.pathname)}
            </span>
          </a>
        </li>
      {/if}
    {/each}
  </ul>
{/if}

{#if response.RelatedTopics.length}
  <h2 class="text-nord6/50">related queries</h2>

  <ul>
    {#each response.RelatedTopics as topic}
      {#if topic.FirstURL}
        {@const q = topic.FirstURL.split("/")
          .reverse()[0]
          .replaceAll("_", "%20")
          .toLowerCase()}
        {#if decodeURIComponent(q) !== query}
          <li class="mb-6">
            <a href={`/?q=${q}`} class="group flex items-center gap-2">
              <Search class="size-4 shrink-0" />
              <div class="truncate">
                <span
                  class="truncate group-hover:underline"
                  style={`view-transition-name: ${decodeURIComponent(q).replaceAll(" ", "_")}`}
                >
                  {decodeURIComponent(q)}
                </span>
              </div>
            </a>
          </li>
        {/if}
      {/if}
    {/each}
  </ul>
{/if}

// components/pages/ResultsPage.tsx
import { DdgResponse } from "@/lib/types";
import { LinkIcon, SearchIcon } from "lucide-react";
import Link from "next/link";

function stripTrailingSlash(str: string) {
  return str.endsWith("/") ? str.slice(0, -1) : str;
}

export default function ResultsPage({
  result,
  query,
}: {
  result: DdgResponse;
  query: string;
}) {
  return (
    <>
      {!!result.Heading && <h1>{result.Heading}</h1>}

      {!!result.Abstract && (
        <aside>
          <div className="flex md:flex-row flex-col gap-6">
            {!!result.Image && (
              <img
                src={`https://duckduckgo.com${result.Image}`}
                alt={result.Heading}
                className="md:order-1 mb-2 rounded w-32 h-fit object-cover object-top"
              />
            )}

            <p>{result.Abstract}</p>
          </div>
        </aside>
      )}

      {!!result.Results?.length && (
        <>
          <h2 className="text-nord6/50">links</h2>

          <ul>
            {result.Results.map((result) => {
              if (result.FirstURL) {
                const url = new URL(result.FirstURL);
                return (
                  <li key={result.FirstURL} className="mb-6">
                    <a
                      href={result.FirstURL}
                      className="group flex items-center gap-2"
                    >
                      <LinkIcon className="size-4 shrink-0" />

                      <span className="group-hover:underline truncate">
                        {url.hostname.replace("www.", "") +
                          stripTrailingSlash(url.pathname)}
                      </span>
                    </a>
                  </li>
                );
              }
            })}
          </ul>
        </>
      )}

      {result.RelatedTopics?.length
        ? (
          <>
            <h2 className="text-nord6/50">related queries</h2>

            <ul>
              {result.RelatedTopics.map((topic) => {
                if (!topic.FirstURL) {
                  return null;
                }

                const q = topic.FirstURL.split("/")
                  .reverse()[0]
                  .replaceAll("_", "%20")
                  .toLowerCase();

                if (decodeURIComponent(q) !== query) {
                  return (
                    <li key={q} className="mb-6">
                      <Link
                        href={`/?q=${q}`}
                        className="group flex items-center gap-2"
                      >
                        <SearchIcon className="size-4 shrink-0" />
                        <div className="truncate">
                          <span className="group-hover:underline truncate">
                            {decodeURIComponent(q)}
                          </span>
                        </div>
                      </Link>
                    </li>
                  );
                }
                return null;
              })}
            </ul>
          </>
        )
        : <h3>No results found :(</h3>}
    </>
  );
}
